------------------------------------------------------------
-- PROYECTO BASE DE DATOS I - MUNDIAL 2026
-- SCRIPT 01: CREACIÓN DE TABLAS
-- SGBD: ORACLE
------------------------------------------------------------

------------------------------------------------------------
-- TABLA: USUARIO
------------------------------------------------------------
CREATE TABLE usuario (
                         id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         username VARCHAR2(50) NOT NULL,
                         password VARCHAR2(100) NOT NULL,
                         rol VARCHAR2(20) NOT NULL,

                         CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
                         CONSTRAINT uk_usuario_username UNIQUE (username),
                         CONSTRAINT ck_usuario_rol CHECK (
                             rol IN ('ADMINISTRADOR', 'TRADICIONAL', 'ESPORADICO')
                             )
);

------------------------------------------------------------
-- TABLA: BITACORA
------------------------------------------------------------
CREATE TABLE bitacora (
                          id_bitacora NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          id_usuario NUMBER NOT NULL,
                          fecha_hora_ingreso TIMESTAMP NOT NULL,
                          fecha_hora_salida TIMESTAMP,

                          CONSTRAINT pk_bitacora PRIMARY KEY (id_bitacora),
                          CONSTRAINT fk_bitacora_usuario FOREIGN KEY (id_usuario)
                              REFERENCES usuario(id_usuario)
);

------------------------------------------------------------
-- TABLA: CONFEDERACION
------------------------------------------------------------
CREATE TABLE confederacion (
                               id_confederacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                               nombre VARCHAR2(80) NOT NULL,
                               continente VARCHAR2(80) NOT NULL,

                               CONSTRAINT pk_confederacion PRIMARY KEY (id_confederacion),
                               CONSTRAINT uk_confederacion_nombre UNIQUE (nombre)
);

------------------------------------------------------------
-- TABLA: GRUPO_MUNDIAL
------------------------------------------------------------
CREATE TABLE grupo_mundial (
                               id_grupo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                               nombre CHAR(1) NOT NULL,

                               CONSTRAINT pk_grupo_mundial PRIMARY KEY (id_grupo),
                               CONSTRAINT uk_grupo_mundial_nombre UNIQUE (nombre),
                               CONSTRAINT ck_grupo_mundial_nombre CHECK (
                                   nombre IN ('A','B','C','D','E','F','G','H','I','J','K','L')
                                   )
);

------------------------------------------------------------
-- TABLA: PAIS
------------------------------------------------------------
CREATE TABLE pais (
                      id_pais NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                      nombre VARCHAR2(80) NOT NULL,
                      es_anfitrion CHAR(1) DEFAULT 'N' NOT NULL,
                      id_confederacion NUMBER NOT NULL,

                      CONSTRAINT pk_pais PRIMARY KEY (id_pais),
                      CONSTRAINT uk_pais_nombre UNIQUE (nombre),
                      CONSTRAINT ck_pais_anfitrion CHECK (es_anfitrion IN ('S','N')),
                      CONSTRAINT fk_pais_confederacion FOREIGN KEY (id_confederacion)
                          REFERENCES confederacion(id_confederacion)
);

------------------------------------------------------------
-- TABLA: EQUIPO
------------------------------------------------------------
CREATE TABLE equipo (
                        id_equipo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        nombre VARCHAR2(80) NOT NULL,
                        fecha_fundacion DATE,
                        id_pais NUMBER NOT NULL,
                        id_grupo NUMBER NOT NULL,

                        CONSTRAINT pk_equipo PRIMARY KEY (id_equipo),
                        CONSTRAINT uk_equipo_nombre UNIQUE (nombre),
                        CONSTRAINT fk_equipo_pais FOREIGN KEY (id_pais)
                            REFERENCES pais(id_pais),
                        CONSTRAINT fk_equipo_grupo FOREIGN KEY (id_grupo)
                            REFERENCES grupo_mundial(id_grupo)
);

------------------------------------------------------------
-- TABLA: DIRECTOR_TECNICO
------------------------------------------------------------
CREATE TABLE director_tecnico (
                                  id_director_tecnico NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                                  nombre VARCHAR2(100) NOT NULL,
                                  fecha_nacimiento DATE NOT NULL,
                                  nacionalidad VARCHAR2(80) NOT NULL,
                                  id_equipo NUMBER NOT NULL,

                                  CONSTRAINT pk_director_tecnico PRIMARY KEY (id_director_tecnico),
                                  CONSTRAINT uk_director_equipo UNIQUE (id_equipo),
                                  CONSTRAINT fk_director_equipo FOREIGN KEY (id_equipo)
                                      REFERENCES equipo(id_equipo)
);

------------------------------------------------------------
-- TABLA: POSICION
------------------------------------------------------------
CREATE TABLE posicion (
                          id_posicion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          nombre VARCHAR2(50) NOT NULL,

                          CONSTRAINT pk_posicion PRIMARY KEY (id_posicion),
                          CONSTRAINT uk_posicion_nombre UNIQUE (nombre)
);

------------------------------------------------------------
-- TABLA: JUGADOR
------------------------------------------------------------
CREATE TABLE jugador (
                         id_jugador NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         nombre VARCHAR2(100) NOT NULL,
                         fecha_nacimiento DATE NOT NULL,
                         estatura NUMBER(4,2) NOT NULL,
                         peso NUMBER(5,2) NOT NULL,
                         valor NUMBER(15,2) NOT NULL,
                         id_equipo NUMBER NOT NULL,
                         id_posicion NUMBER NOT NULL,

                         CONSTRAINT pk_jugador PRIMARY KEY (id_jugador),
                         CONSTRAINT ck_jugador_estatura CHECK (estatura > 0),
                         CONSTRAINT ck_jugador_peso CHECK (peso > 0),
                         CONSTRAINT ck_jugador_valor CHECK (valor >= 0),
                         CONSTRAINT fk_jugador_equipo FOREIGN KEY (id_equipo)
                             REFERENCES equipo(id_equipo),
                         CONSTRAINT fk_jugador_posicion FOREIGN KEY (id_posicion)
                             REFERENCES posicion(id_posicion)
);

------------------------------------------------------------
-- TABLA: CIUDAD
------------------------------------------------------------
CREATE TABLE ciudad (
                        id_ciudad NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        nombre VARCHAR2(80) NOT NULL,
                        id_pais NUMBER NOT NULL,

                        CONSTRAINT pk_ciudad PRIMARY KEY (id_ciudad),
                        CONSTRAINT uk_ciudad_pais UNIQUE (nombre, id_pais),
                        CONSTRAINT fk_ciudad_pais FOREIGN KEY (id_pais)
                            REFERENCES pais(id_pais)
);

------------------------------------------------------------
-- TABLA: ESTADIO
------------------------------------------------------------
CREATE TABLE estadio (
                         id_estadio NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         nombre VARCHAR2(100) NOT NULL,
                         capacidad NUMBER NOT NULL,
                         direccion VARCHAR2(150) NOT NULL,
                         id_ciudad NUMBER NOT NULL,

                         CONSTRAINT pk_estadio PRIMARY KEY (id_estadio),
                         CONSTRAINT uk_estadio_nombre UNIQUE (nombre),
                         CONSTRAINT ck_estadio_capacidad CHECK (capacidad BETWEEN 10000 AND 120000),
                         CONSTRAINT fk_estadio_ciudad FOREIGN KEY (id_ciudad)
                             REFERENCES ciudad(id_ciudad)
);

------------------------------------------------------------
-- TABLA: PARTIDO
------------------------------------------------------------
CREATE TABLE partido (
                         id_partido NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         fecha_partido DATE NOT NULL,
                         hora_partido VARCHAR2(5) NOT NULL,
                         id_estadio NUMBER NOT NULL,
                         id_grupo NUMBER NOT NULL,
                         id_equipo_local NUMBER NOT NULL,
                         id_equipo_visitante NUMBER NOT NULL,
                         goles_local NUMBER DEFAULT 0 NOT NULL,
                         goles_visitante NUMBER DEFAULT 0 NOT NULL,
                         estado VARCHAR2(20) DEFAULT 'PROGRAMADO' NOT NULL,

                         CONSTRAINT pk_partido PRIMARY KEY (id_partido),

                         CONSTRAINT fk_partido_estadio FOREIGN KEY (id_estadio)
                             REFERENCES estadio(id_estadio),

                         CONSTRAINT fk_partido_grupo FOREIGN KEY (id_grupo)
                             REFERENCES grupo_mundial(id_grupo),

                         CONSTRAINT fk_partido_equipo_local FOREIGN KEY (id_equipo_local)
                             REFERENCES equipo(id_equipo),

                         CONSTRAINT fk_partido_equipo_visitante FOREIGN KEY (id_equipo_visitante)
                             REFERENCES equipo(id_equipo),

                         CONSTRAINT ck_partido_goles_local CHECK (goles_local >= 0),
                         CONSTRAINT ck_partido_goles_visitante CHECK (goles_visitante >= 0),

                         CONSTRAINT ck_partido_estado CHECK (
                             estado IN ('PROGRAMADO', 'EN JUEGO', 'FINALIZADO', 'CANCELADO')
                             ),

                         CONSTRAINT ck_partido_equipos_diferentes CHECK (
                             id_equipo_local <> id_equipo_visitante
                             ),

                         CONSTRAINT uk_partido_estadio_fecha_hora UNIQUE (
                                                                          fecha_partido,
                                                                          hora_partido,
                                                                          id_estadio
                             )
);

------------------------------------------------------------
-- ÍNDICES PARA MEJORAR CONSULTAS
------------------------------------------------------------
CREATE INDEX idx_bitacora_usuario ON bitacora(id_usuario);
CREATE INDEX idx_pais_confederacion ON pais(id_confederacion);
CREATE INDEX idx_equipo_pais ON equipo(id_pais);
CREATE INDEX idx_equipo_grupo ON equipo(id_grupo);
CREATE INDEX idx_jugador_equipo ON jugador(id_equipo);
CREATE INDEX idx_jugador_posicion ON jugador(id_posicion);
CREATE INDEX idx_ciudad_pais ON ciudad(id_pais);
CREATE INDEX idx_estadio_ciudad ON estadio(id_ciudad);
CREATE INDEX idx_partido_estadio ON partido(id_estadio);
CREATE INDEX idx_partido_grupo ON partido(id_grupo);
CREATE INDEX idx_partido_local ON partido(id_equipo_local);
CREATE INDEX idx_partido_visitante ON partido(id_equipo_visitante);

COMMIT;